import type { ProductPageContent } from "../lib/product-pages";
import { ArrowRight, Check, CircleCheck } from "lucide-react";
import { appLink } from "../lib/config";
import Footer from "./Footer";
import Header from "./Header";

export default function ProductMarketingPage({ content }: { content: ProductPageContent }) {
  return <div className="proof-page product-page"><Header /><main><section className="product-hero"><div className="marketing-container"><p className="proof-eyebrow"><span /> {content.eyebrow}</p><h1>{content.title}<br />for the way you sell.</h1><p>{content.situation}</p><a className="proof-button proof-button-primary" href={appLink("/register")}>Start Free <ArrowRight size={17} /></a></div></section><section className="product-workflow"><div className="marketing-container"><p className="proof-eyebrow"><span /> THE WORKFLOW</p><h2>One clear next step at a time.</h2><div className="product-steps">{content.workflow.map((step, index) => <article key={step}><span>0{index + 1}</span><strong>{step}</strong></article>)}</div></div></section><section className="product-benefits"><div className="marketing-container"><div><p className="proof-eyebrow"><span /> WHAT CHANGES</p><h2>Less chasing. A better record of the business.</h2></div><ul>{content.benefits.map((benefit) => <li key={benefit}><Check size={18} />{benefit}</li>)}</ul></div></section><section className="product-faq"><div className="marketing-container"><p className="proof-eyebrow"><span /> QUESTIONS</p><h2>Built around the details that matter.</h2>{content.faq.map(([question, answer]) => <article key={question}><CircleCheck size={18} /><div><strong>{question}</strong><p>{answer}</p></div></article>)}</div></section><section className="story-final"><div className="marketing-container"><p className="proof-eyebrow"><span /> PULCHRIFLOW</p><h2>One business underneath every sale.</h2><a className="proof-button proof-button-primary" href={appLink("/register")}>Start Free <ArrowRight size={17} /></a></div></section></main><Footer /></div>;
}
